version: "3.8"
services:
  billing:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan serve --host=0.0.0.0"
    volumes:
      - .:/app
    ports:
      - 8001:8000
    depends_on:
      - billing_service

  billing_service_queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: "php artisan queue:work"
    depends_on:
      - billing_service

  billing_service:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: billing_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33061:3306
